language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - pytest --cov=. --cov-report term-missing
branches:
  only:
   - live
   - beta
   - dev
   - /^Release\/.*$/
after_success:
    - coveralls
